# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from firebase_service_python import order_pb2 as firebase__service__python_dot_Protos_dot_order__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class OrderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateOrder = channel.unary_unary(
                '/OrderService.OrderService/CreateOrder',
                request_serializer=firebase__service__python_dot_Protos_dot_order__pb2.OrderCreate.SerializeToString,
                response_deserializer=firebase__service__python_dot_Protos_dot_order__pb2.Order.FromString,
                )
        self.DeleteOrder = channel.unary_unary(
                '/OrderService.OrderService/DeleteOrder',
                request_serializer=firebase__service__python_dot_Protos_dot_order__pb2.Orderid.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetOrder = channel.unary_unary(
                '/OrderService.OrderService/GetOrder',
                request_serializer=firebase__service__python_dot_Protos_dot_order__pb2.Orderid.SerializeToString,
                response_deserializer=firebase__service__python_dot_Protos_dot_order__pb2.Order.FromString,
                )
        self.GetOrdersByUserId = channel.unary_unary(
                '/OrderService.OrderService/GetOrdersByUserId',
                request_serializer=firebase__service__python_dot_Protos_dot_order__pb2.Userid.SerializeToString,
                response_deserializer=firebase__service__python_dot_Protos_dot_order__pb2.Orders.FromString,
                )


class OrderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrdersByUserId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrder,
                    request_deserializer=firebase__service__python_dot_Protos_dot_order__pb2.OrderCreate.FromString,
                    response_serializer=firebase__service__python_dot_Protos_dot_order__pb2.Order.SerializeToString,
            ),
            'DeleteOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteOrder,
                    request_deserializer=firebase__service__python_dot_Protos_dot_order__pb2.Orderid.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrder,
                    request_deserializer=firebase__service__python_dot_Protos_dot_order__pb2.Orderid.FromString,
                    response_serializer=firebase__service__python_dot_Protos_dot_order__pb2.Order.SerializeToString,
            ),
            'GetOrdersByUserId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrdersByUserId,
                    request_deserializer=firebase__service__python_dot_Protos_dot_order__pb2.Userid.FromString,
                    response_serializer=firebase__service__python_dot_Protos_dot_order__pb2.Orders.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'OrderService.OrderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/OrderService.OrderService/CreateOrder',
            firebase__service__python_dot_Protos_dot_order__pb2.OrderCreate.SerializeToString,
            firebase__service__python_dot_Protos_dot_order__pb2.Order.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/OrderService.OrderService/DeleteOrder',
            firebase__service__python_dot_Protos_dot_order__pb2.Orderid.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/OrderService.OrderService/GetOrder',
            firebase__service__python_dot_Protos_dot_order__pb2.Orderid.SerializeToString,
            firebase__service__python_dot_Protos_dot_order__pb2.Order.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOrdersByUserId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/OrderService.OrderService/GetOrdersByUserId',
            firebase__service__python_dot_Protos_dot_order__pb2.Userid.SerializeToString,
            firebase__service__python_dot_Protos_dot_order__pb2.Orders.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
