# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: firebase_service_python/Protos/order.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*firebase_service_python/Protos/order.proto\x12\x0cOrderService\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\\\n\nTicketStub\x12\x12\n\nmovie_uuid\x18\x01 \x01(\t\x12\x14\n\x0ctheater_room\x18\x02 \x01(\x05\x12\x12\n\nmovie_time\x18\x03 \x01(\t\x12\x10\n\x08seat_num\x18\x04 \x01(\t\"\x16\n\x06Userid\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"\x17\n\x07Orderid\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"L\n\rPaymentMethod\x12\x0e\n\x06\x63\x63_num\x18\x01 \x01(\t\x12\x10\n\x08\x65xp_date\x18\x02 \x01(\t\x12\x0b\n\x03\x63vv\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\"\x19\n\x06IsPaid\x12\x0f\n\x07is_paid\x18\x01 \x01(\x08\"\x83\x01\n\x0bOrderCreate\x12\x11\n\tuser_uuid\x18\x01 \x01(\t\x12\x10\n\x08seat_num\x18\x02 \x03(\t\x12\x14\n\x0ctheater_room\x18\x03 \x01(\x05\x12\x12\n\nmovie_time\x18\x04 \x01(\t\x12%\n\x07is_paid\x18\x05 \x01(\x0b\x32\x14.OrderService.IsPaid\"\xac\x01\n\x05Order\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x11\n\tuser_uuid\x18\x02 \x01(\t\x12)\n\x07tickets\x18\x03 \x03(\x0b\x32\x18.OrderService.TicketStub\x12%\n\x07is_paid\x18\x04 \x01(\x0b\x32\x14.OrderService.IsPaid\x12\x30\n\x0c\x64\x61te_created\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"1\n\x06Orders\x12\'\n\norder_list\x18\x01 \x03(\x0b\x32\x13.OrderService.Order2\x8c\x02\n\x0cOrderService\x12?\n\x0b\x43reateOrder\x12\x19.OrderService.OrderCreate\x1a\x13.OrderService.Order\"\x00\x12>\n\x0b\x44\x65leteOrder\x12\x15.OrderService.Orderid\x1a\x16.google.protobuf.Empty\"\x00\x12\x38\n\x08GetOrder\x12\x15.OrderService.Orderid\x1a\x13.OrderService.Order\"\x00\x12\x41\n\x11GetOrdersByUserId\x12\x14.OrderService.Userid\x1a\x14.OrderService.Orders\"\x00\x42\x15\xaa\x02\x12OrderServiceClientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'firebase_service_python.Protos.order_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\022OrderServiceClient'
  _TICKETSTUB._serialized_start=122
  _TICKETSTUB._serialized_end=214
  _USERID._serialized_start=216
  _USERID._serialized_end=238
  _ORDERID._serialized_start=240
  _ORDERID._serialized_end=263
  _PAYMENTMETHOD._serialized_start=265
  _PAYMENTMETHOD._serialized_end=341
  _ISPAID._serialized_start=343
  _ISPAID._serialized_end=368
  _ORDERCREATE._serialized_start=371
  _ORDERCREATE._serialized_end=502
  _ORDER._serialized_start=505
  _ORDER._serialized_end=677
  _ORDERS._serialized_start=679
  _ORDERS._serialized_end=728
  _ORDERSERVICE._serialized_start=731
  _ORDERSERVICE._serialized_end=999
# @@protoc_insertion_point(module_scope)
