# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x12\x0cOrderService\x1a\x1fgoogle/protobuf/timestamp.proto\"Y\n\x06Ticket\x12\x11\n\tMovieuuid\x18\x01 \x01(\t\x12\x14\n\x0ctheater_room\x18\x02 \x01(\x05\x12\x11\n\tMovieTime\x18\x03 \x01(\t\x12\x13\n\x0bseat_number\x18\x04 \x01(\t\"\x16\n\x06Userid\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"\x17\n\x07Orderid\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"J\n\rPaymentMethod\x12\r\n\x05\x63\x63Num\x18\x01 \x01(\t\x12\x0f\n\x07\x65xpDate\x18\x02 \x01(\t\x12\x0b\n\x03\x63vv\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\"\x1b\n\x0bPaymentType\x12\x0c\n\x04type\x18\x01 \x01(\t\"\x96\x01\n\x08OrderOut\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x13\n\x0bticket_uuid\x18\x02 \x03(\t\x12\x33\n\x0epayment_method\x18\x03 \x01(\x0b\x32\x1b.OrderService.PaymentMethod\x12\x30\n\x0c\x64\x61te_created\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xa3\x01\n\x07OrderIn\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0e\n\x06userid\x18\x02 \x01(\t\x12\x13\n\x0bticket_uuid\x18\x03 \x03(\t\x12\x33\n\x0epayment_method\x18\x04 \x01(\x0b\x32\x1b.OrderService.PaymentMethod\x12\x30\n\x0c\x64\x61te_created\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\xcf\x01\n\x0cOrderService\x12>\n\x0b\x43reateOrder\x12\x16.OrderService.OrderOut\x1a\x15.OrderService.OrderIn\"\x00\x12:\n\x08GetOrder\x12\x15.OrderService.Orderid\x1a\x15.OrderService.OrderIn\"\x00\x12\x43\n\x10GetOrdersForUser\x12\x14.OrderService.Userid\x1a\x15.OrderService.OrderIn\"\x00\x30\x01\x42\x0f\xaa\x02\x0cOrderServiceb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\014OrderService'
  _TICKET._serialized_start=62
  _TICKET._serialized_end=151
  _USERID._serialized_start=153
  _USERID._serialized_end=175
  _ORDERID._serialized_start=177
  _ORDERID._serialized_end=200
  _PAYMENTMETHOD._serialized_start=202
  _PAYMENTMETHOD._serialized_end=276
  _PAYMENTTYPE._serialized_start=278
  _PAYMENTTYPE._serialized_end=305
  _ORDEROUT._serialized_start=308
  _ORDEROUT._serialized_end=458
  _ORDERIN._serialized_start=461
  _ORDERIN._serialized_end=624
  _ORDERSERVICE._serialized_start=627
  _ORDERSERVICE._serialized_end=834
# @@protoc_insertion_point(module_scope)
